export const CHANGE_DESKTOP_ITEMS_COUNT = 'CHANGE_DESKTOP_ITEMS_COUNT';
export const CHANGE_MOBILE_ITEMS_COUNT = 'CHANGE_MOBILE_ITEMS_COUNT';
export const CHANGE_SLIDER_ITEMS_COUNT = 'CHANGE_SLIDER_ITEMS_COUNT';
